import { ArenaV2Adapter } from '../../src/simulation/arenaAdapter.ts';
import { createInitialCharacterV2 } from '../../src/simulation/character.ts';
const canvas=document.querySelector('#scene'),ctx=canvas.getContext('2d'),map=new Image(),bunny=new Image(),goblin=new Image();ctx.imageSmoothingEnabled=false;
const load=(img,src)=>new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=src});await Promise.all([load(map,'/fx/Mine.png'),load(bunny,'../isometric-player/south.png'),load(goblin,'/Sunnyside_World_Assets/Characters/Goblin/PNG/spr_walk_strip8.png')]);
const W=map.naturalWidth,H=map.naturalHeight,mask=document.createElement('canvas'),mx=mask.getContext('2d',{willReadFrequently:true});mask.width=W;mask.height=H;
const player={x:760,y:520,r:10},keys=new Set(),mobs=[{id:'mine-test-goblin-1',monsterType:'mineGoblin',x:570,y:390,t:0,hp:1,maxHp:1,dead:false,aggroRange:150},{id:'mine-test-goblin-2',monsterType:'mineGoblin',x:1020,y:440,t:2.2,hp:1,maxHp:1,dead:false,aggroRange:150},{id:'mine-test-goblin-3',monsterType:'mineGoblin',x:420,y:690,t:4.4,hp:1,maxHp:1,dead:false,aggroRange:150}];let editing=true,painting=false,erase=false,brush=42,pointer={x:0,y:0,inside:false};
const SAVE_KEY='bunny-world:v2:arena-character';
function loadCharacter(){try{const v=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(v?.schemaVersion===2)return v}catch{}return createInitialCharacterV2('arena-player','Arena Bunny')}
function saveCharacter(c){localStorage.setItem(SAVE_KEY,JSON.stringify(c))}
const arena=new ArenaV2Adapter({zoneId:'mine',player,monsters:mobs,character:loadCharacter(),weaponFamily:'dagger',walkableContains:({x,y})=>walkable(x,y),onReward:(reward,c)=>{saveCharacter(c);status.textContent=`KILL! +${reward.exp} EXP · Lv.${c.level} · Gold ${c.gold}`;}});
function nearestLiving(){let best=null,d=Infinity;for(const m of mobs){if(m.dead)continue;const q=Math.hypot(m.x-player.x,m.y-player.y);if(q<d){d=q;best=m}}return best&&d<=95?best:null}
function attack(){if(editing)return;const m=nearestLiving();if(!m){status.textContent='No monster in melee range';return}const result=arena.basicAttack(m.id);if(!result.accepted)status.textContent=`Attack: ${result.reason||'not ready'}`}
function combatHud(){const c=arena.character,p=arena.simulation.world.players.get(arena.playerId);return `Lv.${c.level} · EXP ${c.exp} · HP ${Math.ceil(p?.hp||0)}/${Math.ceil(p?.maxHp||0)} · Gold ${c.gold}`;}
function loadMask(){const saved=localStorage.getItem('bunny-world:mine-walkable-mask');if(!saved)return;const im=new Image();im.onload=()=>mx.drawImage(im,0,0);im.src=saved}loadMask();
const $=s=>document.querySelector(s),paintBtn=$('#paint'),eraseBtn=$('#erase'),status=$('#status');paintBtn.classList.add('active');
function canvasPoint(e){const r=canvas.getBoundingClientRect(),sx=canvas.width/r.width,sy=canvas.height/r.height,scale=Math.min(canvas.width/W,canvas.height/H),ox=(canvas.width-W*scale)/2,oy=(canvas.height-H*scale)/2;return{x:((e.clientX-r.left)*sx-ox)/scale,y:((e.clientY-r.top)*sy-oy)/scale}}
function dab(p){if(p.x<0||p.y<0||p.x>W||p.y>H)return;mx.save();mx.globalCompositeOperation=erase?'destination-out':'source-over';mx.fillStyle='#fff';mx.beginPath();mx.arc(p.x,p.y,brush/2,0,Math.PI*2);mx.fill();mx.restore()}
canvas.addEventListener('pointerdown',e=>{if(!editing)return;painting=true;canvas.setPointerCapture(e.pointerId);const p=canvasPoint(e);pointer={...p,inside:true};dab(p)});
canvas.addEventListener('pointermove',e=>{const p=canvasPoint(e);pointer={...p,inside:true};if(painting&&editing)dab(p)});
canvas.addEventListener('pointerup',()=>painting=false);canvas.addEventListener('pointerleave',()=>pointer.inside=false);
paintBtn.onclick=()=>{erase=false;paintBtn.classList.add('active');eraseBtn.classList.remove('active')};eraseBtn.onclick=()=>{erase=true;eraseBtn.classList.add('active');paintBtn.classList.remove('active')};
$('#brush').oninput=e=>{brush=Number(e.target.value);$('#brush-value').textContent=brush};$('#clear').onclick=()=>{if(confirm('Clear all painted walkable area?'))mx.clearRect(0,0,W,H)};
$('#save').onclick=()=>{localStorage.setItem('bunny-world:mine-walkable-mask',mask.toDataURL('image/png'));status.textContent='Saved locally · walkable mask persisted'};
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#export-mask').onclick=()=>{mask.toBlob(blob=>{if(blob)downloadBlob(blob,'mine_walkable.png')},'image/png');status.textContent='Exported mine_walkable.png'};
$('#export-data').onclick=()=>{const data={version:1,id:'mine-image-test',name:'Goblin Mine Image Test',image:'/fx/Mine.png',walkableMask:'mine_walkable.png',width:W,height:H,playerSpawn:{x:Math.round(player.x),y:Math.round(player.y)},monsterSpawns:mobs.map((m,i)=>({id:`mine-goblin-${i+1}`,type:'goblin',x:Math.round(m.x),y:Math.round(m.y)})),collisionMode:'walkable-mask',maskRule:'alpha>20 = walkable'};downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'mine.json');status.textContent='Exported mine.json'};
$('#play').onclick=()=>{if(editing&&!walkable(player.x,player.y)){/* Put Bunny onto the nearest painted pixel so Play Test never starts trapped. */const data=mx.getImageData(0,0,W,H).data;let best=null,bestD=Infinity;for(let y=0;y<H;y+=4)for(let x=0;x<W;x+=4){if(data[(y*W+x)*4+3]>20){const d=(x-player.x)**2+(y-player.y)**2;if(d<bestD){bestD=d;best={x,y}}}}if(best)Object.assign(player,best);else{status.textContent='Paint some green walkable ground first';return;}}editing=!editing;$('#play').textContent=editing?'PLAY TEST':'BACK TO EDITOR';status.textContent=editing?'Editor mode · drag on the map':'Play test · WASD / arrows · collision uses your green paint';};
function walkable(x,y,r=9){/* Sample the feet, not a 5-point cross: brush-painted corridors stay usable. */try{const a=mx.getImageData(Math.max(0,Math.min(W-1,x|0)),Math.max(0,Math.min(H-1,y|0)),1,1).data[3];return a>20}catch{return false}}
function move(o,dx,dy){if(walkable(o.x+dx,o.y,o.r||9))o.x+=dx;if(walkable(o.x,o.y+dy,o.r||9))o.y+=dy}
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.code==='Space'){e.preventDefault();attack()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function drawEntity(img,x,y,frame=0){const sx=img===goblin?frame*64:0,sw=img===goblin?64:img.width,sh=img===goblin?64:img.height;ctx.drawImage(img,sx,0,sw,sh,x-24,y-48,48,48)}
let last=performance.now();function tick(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(!editing){let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),l=Math.hypot(dx,dy)||1;move(player,dx/l*170*dt,dy/l*170*dt);mobs.forEach((m,i)=>{m.t+=dt;const tx=player.x-m.x,ty=player.y-m.y,ll=Math.hypot(tx,ty)||1;if(m.dead)return;if(ll<330)move(m,tx/ll*55*dt,ty/ll*55*dt);else move(m,Math.cos(m.t+i)*22*dt,Math.sin(m.t*.8+i)*18*dt)});arena.syncFromPresentationPositions();arena.step(dt*1000);if(Math.floor(now/500)!==Math.floor((now-dt*1000)/500))status.textContent=combatHud()}
ctx.clearRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/W,canvas.height/H),ox=(canvas.width-W*scale)/2,oy=(canvas.height-H*scale)/2;ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);ctx.drawImage(map,0,0,W,H);if(editing){ctx.save();ctx.globalAlpha=.24;ctx.globalCompositeOperation='source-over';ctx.drawImage(mask,0,0);ctx.globalCompositeOperation='source-atop';ctx.fillStyle='#28ff78';ctx.fillRect(0,0,W,H);ctx.restore();if(pointer.inside){ctx.strokeStyle=erase?'#ff5c5c':'#66ff99';ctx.lineWidth=3/scale;ctx.beginPath();ctx.arc(pointer.x,pointer.y,brush/2,0,Math.PI*2);ctx.stroke()}}mobs.forEach(m=>{if(m.dead)return;drawEntity(goblin,m.x,m.y,Math.floor(now/130)%8);ctx.fillStyle='#250b0b';ctx.fillRect(m.x-22,m.y-55,44,5);ctx.fillStyle='#ef4949';ctx.fillRect(m.x-22,m.y-55,44*Math.max(0,m.hp/m.maxHp),5)});drawEntity(bunny,player.x,player.y);ctx.restore();requestAnimationFrame(tick)}requestAnimationFrame(tick);