import{describe,expect,it}from'vitest';import{ArenaV2Adapter}from'./arenaAdapter';
describe('Arena V2 adapter',()=>{
 it('makes simulation the only HP writer',()=>{const player={x:0,y:0};const monsters=[{id:'m1',x:20,y:0,hp:999,maxHp:999,dead:false}];const a=new ArenaV2Adapter({zoneId:'forest1',player,monsters,random:()=>0});expect(monsters[0].hp).not.toBe(999);const before=monsters[0].hp;const r=a.basicAttack('m1');expect(r.accepted).toBe(true);expect(monsters[0].hp).toBeLessThan(before)});
 it('routes full-auto through the same authoritative command path',()=>{const player={x:0,y:0};const monsters=[{id:'m1',x:20,y:0,hp:1,maxHp:1,dead:false}];const a=new ArenaV2Adapter({zoneId:'forest1',player,monsters,random:()=>0});const before=a.simulation.world.monsters.get('m1')!.hp;const auto=a.autoStep('fullAuto');expect(auto?.command.type).toBe('basicAttack');expect(auto?.result.accepted).toBe(true);expect(a.simulation.world.monsters.get('m1')!.hp).toBeLessThan(before)});
 it('finishes the current monster before HP rest, then pauses until resume HP',()=>{const player={x:0,y:0};const monsters=[{id:'m1',x:20,y:0,hp:100,maxHp:100,dead:false},{id:'m2',x:25,y:0,hp:100,maxHp:100,dead:false}];const a=new ArenaV2Adapter({zoneId:'forest1',player,monsters,random:()=>0});const p=a.simulation.world.players.get(a.playerId)!;p.hp=p.maxHp*.30;const fighting=a.autoStep('fullAuto',{restEnabled:true,restBelowHpFraction:.30,resumeAboveHpFraction:.75});expect(fighting?.command.type).toBe('basicAttack');const m1=a.simulation.world.monsters.get('m1')!;m1.hp=1;p.nextBasicAttackAtMs=0;const kill=a.autoStep('fullAuto',{restEnabled:true,restBelowHpFraction:.30,resumeAboveHpFraction:.75});expect(kill?.result.accepted).toBe(true);expect(m1.alive).toBe(false);const resting=a.autoStep('fullAuto',{restEnabled:true,restBelowHpFraction:.30,resumeAboveHpFraction:.75});expect(resting?.command).toMatchObject({type:'move',direction:{x:0,y:0}});p.hp=p.maxHp*.75;const resumed=a.autoStep('fullAuto',{restEnabled:true,restBelowHpFraction:.30,resumeAboveHpFraction:.75});expect(resumed?.command.type).toBe('basicAttack')});
 it('copies presentation positions inward but never presentation HP',()=>{const player={x:0,y:0};const monsters=[{id:'m1',x:20,y:0,hp:1,maxHp:1,dead:false}];const a=new ArenaV2Adapter({zoneId:'forest1',player,monsters,random:()=>0});const authoritative=a.simulation.world.monsters.get('m1')!.hp;monsters[0].hp=999999;monsters[0].x=25;a.syncFromPresentationPositions();expect(a.simulation.world.monsters.get('m1')!.hp).toBe(authoritative);expect(a.simulation.world.monsters.get('m1')!.position.x).toBe(25)});
 it('commits defeat rewards to authoritative character economy',()=>{const player={x:0,y:0};const monsters=[{id:'mossblob1-0',monsterType:'mossblob1',x:20,y:0,hp:1,maxHp:1,dead:false}];let rewarded=0;const a=new ArenaV2Adapter({zoneId:'forest1',player,monsters,random:()=>0,onReward:(_r,c)=>rewarded=c.gold});const m=a.simulation.world.monsters.get('mossblob1-0')!;m.hp=1;const result=a.basicAttack(m.id);expect(result.accepted).toBe(true);expect(rewarded).toBeGreaterThan(0);expect(a.character.gold).toBe(rewarded);expect(a.character.inventory.copperOre).toBe(1);expect(a.character.weaponMastery.dagger.xp).toBeGreaterThan(0)});
 it('updates reward mastery family when the equipped main weapon changes',()=>{const player={x:0,y:0};const monsters=[{id:'mossblob1-0',monsterType:'mossblob1',x:20,y:0,hp:1,maxHp:1,dead:false}];const a=new ArenaV2Adapter({zoneId:'forest1',player,monsters,weaponFamily:'bow',random:()=>0});const state=a.character;const axe={id:'test-axe',templateId:'mosswoodAxe',slot:'main',rarity:'normal',affixes:[],baseGoldCost:1};state.equipment.instances[axe.id]=axe as any;state.equipment.equippedBySlot.main=axe.id;a.equipmentCommand({type:'equip',equipmentId:axe.id});const m=a.simulation.world.monsters.get('mossblob1-0')!;m.hp=1;a.basicAttack(m.id);expect(a.character.weaponMastery.axe.xp).toBeGreaterThan(0);expect(a.character.weaponMastery.bow.xp).toBe(0)});
 it('owns normal-monster respawn timing authoritatively',()=>{const player={x:0,y:0};const monsters=[{id:'mossblob1-0',monsterType:'mossblob1',x:20,y:0,hp:1,maxHp:1,dead:false}];const a=new ArenaV2Adapter({zoneId:'forest1',player,monsters,random:()=>0});const m=a.simulation.world.monsters.get('mossblob1-0')!;m.hp=1;a.basicAttack(m.id);expect(m.alive).toBe(false);a.step(2799);expect(m.alive).toBe(false);const events=a.step(1);expect(m.alive).toBe(true);expect(m.hp).toBe(m.maxHp);expect(events.some(e=>e.type==='entityRespawned'&&e.entityId===m.id)).toBe(true);expect(m.targetPlayerId).toBeUndefined()});
});