import{describe,expect,it}from'vitest';import{createInitialCharacterV2}from'./character';import{inventoryCategoryFor,isSkillCoreItem}from'./itemTagsV2';import{applySkillCoreCommand}from'./skillCoreService';

describe('inventory item tags and skill core loadout',()=>{
 it('tags canonical and legacy crafting resources instead of Misc',()=>{expect(inventoryCategoryFor('livingMoss')).toBe('Crafting Mat');expect(inventoryCategoryFor('beastPelt')).toBe('Crafting Mat');expect(inventoryCategoryFor('hide')).toBe('Crafting Mat');expect(inventoryCategoryFor('core')).toBe('Crafting Mat');expect(inventoryCategoryFor('copperOre')).toBe('Crafting Mat')});
 it('tags dropped active and movement skills as Skill Core',()=>{expect(isSkillCoreItem('blackHole')).toBe(true);expect(inventoryCategoryFor('dash')).toBe('Skill Core')});
 it('equips an owned core without consuming it and supports replacement',()=>{let s=createInitialCharacterV2('c');s.inventory.blackHole=1;s.inventory.fireball=1;s=applySkillCoreCommand(s,{type:'equipCore',coreId:'blackHole',slot:0});expect(s.skills.active[0]).toBe('blackHole');expect(s.inventory.blackHole).toBe(1);s=applySkillCoreCommand(s,{type:'equipCore',coreId:'fireball',slot:0});expect(s.skills.active[0]).toBe('fireball');expect(s.inventory.blackHole).toBe(1)});
 it('keeps movement cores in the dedicated movement slot',()=>{let s=createInitialCharacterV2('c');s.inventory.dash=1;s=applySkillCoreCommand(s,{type:'equipMovementCore',coreId:'dash'});expect(s.skills.movement).toBe('dash');expect(()=>applySkillCoreCommand(s,{type:'equipCore',coreId:'dash',slot:0})).toThrow('movement-core-requires-movement-slot')});
 it('equips owned skill modifiers into either mod slot',()=>{let s=createInitialCharacterV2('c');s.inventory.blackHole=1;s.inventory.lingering=1;s=applySkillCoreCommand(s,{type:'equipCore',coreId:'blackHole',slot:0});s=applySkillCoreCommand(s,{type:'equipModifier',coreId:'blackHole',modifierId:'lingering',modSlot:1});expect(s.skills.modifiersByActive.blackHole[1]).toBe('lingering');expect(s.inventory.lingering).toBe(1)});
 it('rejects cores the character does not own',()=>expect(()=>applySkillCoreCommand(createInitialCharacterV2('c'),{type:'equipCore',coreId:'blackHole',slot:0})).toThrow('skill-core-not-owned'));
});