import {bayerLevel,fbm,hash2,valueNoise} from './noise';
import {FOREST_PALETTE,clampLevel,type RGB} from './palette';
export interface Rect{x0:number;x1:number;y0:number;y1:number}
export interface GroundScene{paths:Rect[];plateaus:Rect[];plateauHeight:number;forestCenter:{x:number;y:number};forestRadius:{x:number;y:number}}
const inside=(x:number,y:number,r:Rect,m=0)=>x>=r.x0-m&&x<=r.x1+m&&y>=r.y0-m&&y<=r.y1+m;
export function pathInside(x:number,y:number,paths:Rect[]){let best=-1e9;for(const r of paths)best=Math.max(best,Math.min(x-r.x0,r.x1-x,y-r.y0,r.y1-y));return best}
export function pathDistance(x:number,y:number,paths:Rect[]){let best=1e9;for(const r of paths){const dx=Math.max(r.x0-x,0,x-r.x1),dy=Math.max(r.y0-y,0,y-r.y1);best=Math.min(best,Math.hypot(dx,dy))}return best}
export function forestDensity(x:number,y:number,s:GroundScene){const d=Math.hypot((x-s.forestCenter.x)/s.forestRadius.x,(y-s.forestCenter.y)/s.forestRadius.y);const smooth=(a:number,b:number,t:number)=>{t=Math.max(0,Math.min(1,(t-a)/(b-a)));return t*t*(3-2*t)};return Math.max(0,Math.min(1,smooth(.5,.98,d)+(fbm(x*.004+7,y*.004+3)-.5)*.75))}
export function cobbleColor(x:number,y:number,px:number,py:number,s:GroundScene):RGB|null{const rowH=22,row=Math.floor(y/rowH),off=(row&1)*13+hash2(row,7)*6,cw=26,col=Math.floor((x+off)/cw),ccx=(col+.5)*cw-off,ccy=(row+.5)*rowH;if(pathInside(ccx,ccy,s.paths)<hash2(col*3,row)*26-6)return null;const u=x+off-col*cw,v=y-row*rowH;if(u<3||v<3||(u<7&&v<7&&u+v<8)||(u>cw-5&&v>rowH-5&&(cw-u)+(rowH-v)<6))return FOREST_PALETTE.mortar;let l=1+Math.floor(hash2(col,row)*3);if(u<8||v<7)l++;if(u>cw-6||v>rowH-5)l--;if(hash2(px,py)>.9)l--;if(valueNoise(x*.02,y*.02)>.72&&hash2(px*5,py)>.6)return FOREST_PALETTE.grass[2];return FOREST_PALETTE.cobble[clampLevel(l,4)]}
export function groundColor(x:number,y:number,px:number,py:number,s:GroundScene):RGB{if(pathInside(x,y,s.paths)>-8){const c=cobbleColor(x,y,px,py,s);if(c)return c}const dens=forestDensity(x,y,s),dirt=fbm(x*.0055+31,y*.0055+11)-.64,worn=pathDistance(x,y,s.paths)<20+fbm(x*.02,y*.02)*30?.03:-1;if(Math.max(dirt,worn)+(bayerLevel(px,py,.5,16)-7.5)/16*.035>0){let t=.5+(valueNoise(x*.05,y*.05)-.5)*.7-dens*.2;return FOREST_PALETTE.dirt[clampLevel(Math.round(t*4),4)]}let t=.6+(fbm(x*.0035,y*.0035)-.5)*.85-dens*.34;return FOREST_PALETTE.grass[clampLevel(Math.round(t*5+(bayerLevel(px,py,.5,16)-7.5)/16),5)]}
export function cliffColor(which:'x'|'y',e:number,hgt:number,px:number,py:number,s:GroundScene):RGB{const k=which==='x'?-1:0;if(hgt>s.plateauHeight-2-valueNoise(e*.09,3)*7){const l=hgt>s.plateauHeight-2?4:2+(hash2(px,py)>.6?1:0)+k;return FOREST_PALETTE.grass[clampLevel(l,5)]}if(hgt<2.5)return FOREST_PALETTE.cliff[0];const ep=e*.559,row=Math.floor(hgt/8),rowOff=hash2(row,11)*12,bw=14+Math.floor(hash2(row,5)*8),col=Math.floor((ep+rowOff)/bw),lu=(ep+rowOff)-col*bw,lv=hgt-row*8;if(lv<1.2||lu<1.2)return FOREST_PALETTE.cliff[0];let l=2+Math.floor(hash2(col,row)*2)+k;if(lv>6.5)l++;if(lu<3)l--;if(hash2(px*3,py)>.92)l--;if(valueNoise(ep*.12,hgt*.12)>.7&&hgt>s.plateauHeight*.5)return FOREST_PALETTE.bush[clampLevel(l,5)];return FOREST_PALETTE.cliff[clampLevel(l,5)]}
export function plateauAt(x:number,y:number,s:GroundScene){return s.plateaus.some(p=>inside(x,y,p))}
