// Split from game.js (UI). Code moved as-is; see ui/runtime.js for game-state bindings.
import { EQUIPMENT_MASTER_V2, SET_DEFINITIONS_V2 } from '../../../src/simulation/itemMasterV2.ts';
import { iconHtml } from '../../iso-arena-draft/iconFor.js';
import { sim, saveCharacter } from './runtime.js';
import { gearGlyph, prettyItem, showUiError } from './shared.js';
import { bindEquipmentActionButtons, equipmentDetailModal, equipmentUi, itemDetailHtml } from './gear.js';

export const CRAFT_UI_RECIPES=Object.values(EQUIPMENT_MASTER_V2).map(item=>({id:item.id,name:item.name,tier:item.tier,slot:item.slot,type:item.slot==='main'?'Weapon':item.slot==='offhand'?'Offhand':(item.slot==='accessoryLeft'||item.slot==='accessoryRight')?'Accessory':item.slot[0].toUpperCase()+item.slot.slice(1),blueprintId:item.recipe.blueprintId,oreId:item.recipe.oreId,oreQty:item.recipe.oreQty,materials:item.recipe.materials,gold:item.recipe.gold,baseGoldCost:item.baseGoldCost,baseCombat:item.baseCombat,offhandType:item.offhandType,setId:item.setId,requiredLevel:item.requiredLevel,available:item.recipe.available,role:item.role}));
export const CRAFT_SET_BY_ID=new Map(SET_DEFINITIONS_V2.map(set=>[set.id,set]));
export const CRAFT_RARITIES=[['Normal','50%'],['Good','27%'],['Rare','15%'],['Epic','6%'],['Legend','1.7%'],['Mythic','0.28%'],['White Ascended','0.02%']];
export const craftUi={type:'Weapon',tier:'All',selected:'mosswoodSword',batch:1};
export function craftStatLines(stats={}){const labels={atk:'ATK',matk:'MATK',def:'DEF',mdef:'MDEF',maxHp:'HP',crit:'CRIT',aspd:'ASPD',hit:'HIT',flee:'FLEE'};return Object.entries(stats).filter(([,v])=>Number(v)!==0).map(([k,v])=>`<div><span>${labels[k]||k}</span><b>+${v}</b></div>`).join('')||'<div><span>Base Stats</span><b>—</b></div>';}
export function equippedSetCount(setId,c){return Object.values(c.equipment.equippedBySlot).filter(Boolean).map(id=>c.equipment.instances[id]).filter(item=>item?.setId===setId).length;}
export function craftSetDetail(recipe,c){if(!recipe.setId)return '<div class="craft-no-set">No Set Bonus</div>';const set=CRAFT_SET_BY_ID.get(recipe.setId);if(!set)return '';const count=Math.min(set.requiredPieces,equippedSetCount(recipe.setId,c)),active=count>=set.requiredPieces;return `<div class="craft-set-box ${active?'set-active':'set-inactive'}"><div class="craft-set-head"><div><strong>${recipe.name.split(' ')[0]} Set</strong><small>${set.group==='body'?'BODY SET':'ACCESSORY SET'} · ${set.role.toUpperCase()}</small></div><b>${count}/${set.requiredPieces}</b></div>${set.effect.map(effect=>`<p>◆ ${effect}</p>`).join('')}</div>`;}
export function renderCraftWindow(){
 const body=document.getElementById('game-window-body'),c=sim.character,types=['Weapon','Offhand','Armor','Cape','Shoes','Accessory'];if(!body)return;
 let list=CRAFT_UI_RECIPES.filter(r=>r.type===craftUi.type&&(craftUi.tier==='All'||r.tier===Number(craftUi.tier)));if(!list.length)list=CRAFT_UI_RECIPES.filter(r=>craftUi.tier==='All'||r.tier===Number(craftUi.tier));const selected=list.find(r=>r.id===craftUi.selected)||list[0];
 body.innerHTML=`<div class="craft-topbar"><div class="craft-tabs">${types.map(t=>`<button data-craft-type="${t}" class="${craftUi.type===t?'active':''}">${t}</button>`).join('')}</div><label>Tier <select id="craft-tier"><option value="All">All T</option>${[1,2,3,4,5].map(t=>`<option value="${t}" ${String(craftUi.tier)===String(t)?'selected':''}>T${t}</option>`).join('')}</select></label></div><div class="craft-three"><section class="craft-card craft-list"><header>CRAFTING LIST</header>${list.map(r=>`<button data-craft-recipe="${r.id}" class="${selected?.id===r.id?'active':''}"><span class="craft-icon">${iconHtml(r.id,'equipment','◆')}</span><span><strong>${r.name}</strong><small>T${r.tier} · ${r.type}</small></span></button>`).join('')}</section><section class="craft-card craft-detail"><header>ITEM DETAIL</header>${selected?`<div class="craft-preview">${iconHtml(selected.id,'equipment','◆')}</div><div class="craft-detail-title"><h2>${selected.name}</h2><span class="tier-chip">T${selected.tier} · ${selected.type}</span></div><div class="craft-tags"><span>Lv ${selected.requiredLevel}+</span><span>${selected.role.toUpperCase()}</span></div><div class="craft-stat-box"><h3>BASE STATS</h3>${craftStatLines(selected.baseCombat)}</div>${craftSetDetail(selected,c)}<div class="craft-meta"><span>Slot</span><b>${selected.slot.toUpperCase()}</b><span>Required Level</span><b>${selected.requiredLevel}</b><span>Base value</span><b>${selected.baseGoldCost} G</b></div>`:''}</section><section class="craft-card craft-cost"><header>MATERIALS & RARITY</header>${selected?`<div class="craft-materials">${[[selected.blueprintId,1],[selected.oreId,selected.oreQty],...selected.materials.map(m=>[m.itemId,m.qty])].map(([id,q])=>`<div><span class="craft-mat-name">${iconHtml(id,'item','')}${prettyItem(id)}</span><b class="${(c.inventory[id]??0)>=q?'enough':'missing'}">${c.inventory[id]??0} / ${q}</b></div>`).join('')}<div class="gold-cost"><span>Gold</span><b>${c.gold.toLocaleString()} / ${selected.gold.toLocaleString()}</b></div></div><h3>RARITY CHANCE</h3><div class="rarity-chances">${CRAFT_RARITIES.map(([n,p])=>`<span class="rarity-mini rarity-${n.toLowerCase().replace(' ','-')}"><i>${n}</i><b>${p}</b></span>`).join('')}</div><div class="craft-batch-picker"><span>CRAFT QTY</span>${[1,10,20,50].map(q=>`<button data-craft-qty="${q}" class="${craftUi.batch===q?'active':''}">×${q}</button>`).join('')}</div><button class="craft-button" data-craft-now="${selected.id}" ${selected.available?'':'disabled'}>${selected.available?(craftUi.batch===1?'CRAFT':`BATCH CRAFT ×${craftUi.batch}`):'PLANNED'}</button>`:''}</section></div>`;
 body.querySelectorAll('[data-craft-type]').forEach(b=>b.onclick=()=>{craftUi.type=b.dataset.craftType;craftUi.selected='';renderCraftWindow();});body.querySelector('#craft-tier')?.addEventListener('change',e=>{craftUi.tier=e.target.value;craftUi.selected='';renderCraftWindow();});body.querySelectorAll('[data-craft-recipe]').forEach(b=>b.onclick=()=>{craftUi.selected=b.dataset.craftRecipe;renderCraftWindow();});body.querySelectorAll('[data-craft-qty]').forEach(b=>b.onclick=()=>{craftUi.batch=Number(b.dataset.craftQty);renderCraftWindow();});
 body.querySelector('[data-craft-now]')?.addEventListener('click',()=>{const r=CRAFT_UI_RECIPES.find(x=>x.id===selected?.id);if(!r)return;const qty=craftUi.batch||1,recipe={templateId:r.id,slot:r.slot,blueprintId:r.blueprintId,oreId:r.oreId,oreQty:r.oreQty,materials:r.materials,gold:r.gold,baseGoldCost:r.baseGoldCost,baseCombat:r.baseCombat,offhandType:r.offhandType,setId:r.setId,requiredLevel:r.requiredLevel,available:r.available};try{const need=[[r.blueprintId,1],[r.oreId,r.oreQty],...r.materials.map(m=>[m.itemId,m.qty])];if(need.find(([id,n])=>(c.inventory[id]??0)<n*qty)||c.gold<r.gold*qty){showUiError(`Materials/Gold insufficient for ×${qty}`);return;}const made=[];for(let i=0;i<qty;i++){const res=sim.equipmentCommand({type:'craft',recipe});const item=sim.character.equipment.instances[res.createdEquipmentId];if(item)made.push(item);}saveCharacter(sim.character);renderCraftWindow();if(made.length===1)showCraftSuccess(made[0]);else if(made.length)showBatchCraftResults(made,r.name);}catch(error){showUiError(String(error?.message||error));}});
}

export function showCraftSuccess(item){
 const c=sim.character;
 equipmentUi.selectedId=item.id;
 equipmentDetailModal.innerHTML=`<button class="rpg-modal-close" type="button" aria-label="Close">×</button><div class="equipment-detail-card craft-success-card"><div class="craft-success-heading">CRAFT SUCCEEDED!</div>${itemDetailHtml(item,c,false)}</div>`;
 equipmentDetailModal.hidden=false;
 equipmentDetailModal.querySelector('.rpg-modal-close').onclick=()=>equipmentDetailModal.hidden=true;
 bindEquipmentActionButtons(equipmentDetailModal);
}
export function showBatchCraftResults(items,name){let page=0;const pages=[];for(let i=0;i<items.length;i+=10)pages.push(items.slice(i,i+10));const render=()=>{const batch=pages[page],summary=Object.entries(items.reduce((a,x)=>(a[x.rarity]=(a[x.rarity]||0)+1,a),{})).map(([r,n])=>`${r.toUpperCase()} ×${n}`).join(' · ');equipmentDetailModal.innerHTML=`<div class="batch-craft-result"><small>BATCH CRAFT · ${name}</small><h2>REVEAL ${page+1}/${pages.length}</h2><div class="batch-craft-grid">${batch.map(x=>`<div class="batch-craft-drop rarity-${x.rarity}"><span>${iconHtml(x.templateId,'equipment',gearGlyph(x.slot))}</span><strong>${x.rarity.toUpperCase()}</strong></div>`).join('')}</div><p>${summary}</p><button data-batch-next>${page<pages.length-1?'NEXT ×10':'DONE'}</button></div>`;equipmentDetailModal.hidden=false;equipmentDetailModal.querySelector('[data-batch-next]').onclick=()=>{if(page<pages.length-1){page++;render();}else equipmentDetailModal.hidden=true;};};render();}
