// Split from game.js (UI). Code moved as-is; see ui/runtime.js for game-state bindings.
import { inventoryCategoryFor, inventoryItemMeta } from '../../../src/simulation/itemTagsV2.ts';
import { SKILLS_V2 } from '../../../src/simulation/skills.ts';

export const prettyItem=id=>String(id||'').replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
export function showUiError(message){let t=document.querySelector('.equipment-result-toast');if(!t){t=document.createElement('div');t.className='equipment-result-toast';document.body.append(t);}t.className='equipment-result-toast error show';t.textContent=message;clearTimeout(showUiError.timer);showUiError.timer=setTimeout(()=>t.classList.remove('show'),1800);}
export function closeDetailModal(){const modal=document.getElementById('equipment-detail-modal');if(!modal)return;modal.hidden=true;modal.replaceChildren();}
export function bindDetailModalClose(modal){const close=modal.querySelector('.rpg-modal-close');if(close)close.onclick=e=>{e.preventDefault();e.stopPropagation();closeDetailModal();};modal.onclick=e=>{if(e.target===modal)closeDetailModal();};}
export const ITEM_INFO={livingMoss:'Crafting material from Mossblobs.',brutalSpore:'Crafting material from Sporekin.',copperOre:'Early crafting ore.',ironOre:'Forest crafting ore.',moonstoneShard:'Desert crafting ore.',silverOre:'Advanced desert crafting ore.',mithrilOre:'Mine crafting ore.',verdantAetherstone:'Enhancement stone up to +40.',azureAetherstone:'Enhancement stone for +41–80.',violetAetherstone:'Enhancement stone for +81–120.',astraliteStone:'Refinement material.'};
export function gearGlyph(slot){return {armor:'◈',cape:'⌁',shoes:'⌑',accessoryLeft:'◇',accessoryRight:'◇',hat:'♢',face:'◉',mouth:'◆',main:'†',offhand:'◐'}[slot]||'◆';}
export function inventoryCategory(id){return inventoryCategoryFor(id)}
export function itemInfo(id){const skill=SKILLS_V2[id],meta=inventoryItemMeta(id);if(skill&&meta.tags.includes('skill-core'))return `Skill Core: ${skill.name}.`;return ITEM_INFO[id]||(meta.category==='Blueprint'?'Equipment blueprint used for crafting.':meta.category==='Crafting Mat'?'Crafting material.':meta.category==='Upgrading Mat'?'Upgrade material.':'Adventure item.');}
export function showEquipmentError(message){let toast=document.querySelector('.equipment-result-toast');if(!toast){toast=document.createElement('div');toast.className='equipment-result-toast error';(document.getElementById('game-ui')||document.body).append(toast);}toast.className='equipment-result-toast error show';toast.textContent=message;clearTimeout(showEquipmentError.timer);showEquipmentError.timer=setTimeout(()=>toast.classList.remove('show'),1500);}
export function showRefineResult(success){let toast=document.querySelector('.equipment-result-toast');if(!toast){toast=document.createElement('div');toast.className='equipment-result-toast';(document.getElementById('game-ui')||document.body).append(toast);}toast.className='equipment-result-toast '+(success?'success':'fail')+' show';toast.innerHTML=success?'<strong>REFINE SUCCEEDED!</strong><span>Refinement level increased</span>':'<strong>REFINE FAILED</strong><span>Refinement did not succeed</span>';clearTimeout(showRefineResult.timer);showRefineResult.timer=setTimeout(()=>toast.classList.remove('show'),1400);}
