// Split from game.js (UI). Code moved as-is; see ui/runtime.js for game-state bindings.
import { ArenaV2Adapter } from '../../../src/simulation/arenaAdapter.ts';
import { sim, SAVE_KEY } from './runtime.js';
import { presentEventTime } from './eventBanner.js';

export function renderSettings(body){body.innerHTML='<div class="settings-panel"><h3>ACCOUNT</h3><p class="window-note">Reset Account permanently deletes this browser\'s Bunny World character, then starts a new game.</p><button class="danger-button" type="button" data-reset-account>RESET ACCOUNT</button></div>';body.querySelector('[data-reset-account]').onclick=()=>{if(!confirm('Reset your Bunny World account? All character progress, inventory, equipment and skills on this browser will be permanently deleted.'))return;if(!confirm('Are you sure? This cannot be undone.'))return;try{localStorage.removeItem(SAVE_KEY);}catch{}location.reload();};}
// GM event multipliers (dev-only button). Applies to rewards through ArenaV2Adapter.setGmEventMultipliers.
export const gmEvent={enabled:false,exp:2,weaponExp:2,drop:2,gold:2,upgradeItem:2,blueprint:2};
export function applyGmEvent(){const on=gmEvent.enabled;sim.setGmEventMultipliers({exp:on?gmEvent.exp:1,weaponExp:on?gmEvent.weaponExp:1,drop:on?gmEvent.drop:1,gold:on?gmEvent.gold:1,upgradeItem:on?gmEvent.upgradeItem:1,blueprint:on?gmEvent.blueprint:1});presentEventTime(on,gmEvent);}
export function renderGmEventPanel(title,body){title.textContent='GM EVENT CONTROL';const rows=[['exp','CHAR EXP'],['weaponExp','WEAPON EXP'],['drop','DROP'],['gold','GOLD'],['upgradeItem','UPGRADE ITEM'],['blueprint','BLUEPRINT']];body.innerHTML=`<div class="gm-panel"><div class="gm-master"><div><strong>EVENT MODE</strong><small>${gmEvent.enabled?'LIVE':'OFF'}</small></div><label class="gm-switch"><input id="gm-master" data-gm-master type="checkbox" ${gmEvent.enabled?'checked':''}><span></span></label></div><p class="window-note">Set each reward multiplier independently from ×2 to ×10.</p><div class="gm-toggle-list">${rows.map(([k,l])=>`<label><span>${l}</span><div class="gm-multiplier-control"><button type="button" data-gm-minus="${k}">−</button><strong>×${gmEvent[k]}</strong><button type="button" data-gm-plus="${k}">+</button></div></label>`).join('')}</div></div>`;const again=()=>{applyGmEvent();renderGmEventPanel(title,body);};body.querySelector('[data-gm-master]').onchange=e=>{gmEvent.enabled=e.target.checked;again();};body.querySelectorAll('[data-gm-minus]').forEach(b=>b.onclick=()=>{gmEvent[b.dataset.gmMinus]=Math.max(2,gmEvent[b.dataset.gmMinus]-1);again();});body.querySelectorAll('[data-gm-plus]').forEach(b=>b.onclick=()=>{gmEvent[b.dataset.gmPlus]=Math.min(10,gmEvent[b.dataset.gmPlus]+1);again();});}
if(import.meta.env.DEV){const gm=document.createElement('button');gm.dataset.window='GM Event';gm.type='button';gm.innerHTML='GM<span>Event</span>';document.querySelector('.quick-menu')?.insertBefore(gm,document.getElementById('sfx-toggle'));}
